apiVersion: apps/v1
kind: Deployment
metadata:
  name: comments-api-dp
  namespace: api-prd
  labels:
    app: comments-api
spec:
  selector:
    matchLabels:
      app: comments-api
  replicas: 1
  template:
    metadata:
      labels:
        app: comments-api
    spec:
      containers:
        - name: comments-api
          image: us-central1-docker.pkg.dev/lab-terraform-414113/comments-api/main:834214d
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 200m
              memory: 200Mi
      imagePullSecrets:
        - name: container-registry
